### PR TITLE
feature(validation): add more advanced validation in param config

### LINKED ISSUE #10: [FEATURE] Validate request from configure screen
**Is your feature request related to a problem? Please describe.**
Unable to validate connection from Config screen.

**Describe the solution you'd like**
When configuring a FreeStyle job, including one that requires authentication, it would be helpful to have a "Validate" or "Test Connection" to ensure the parameters have been set correctly and the response is as expected, prior to saving the job.

When setting a Credential ID for authentication, an immediate error should display (similar to SCM Git client) if authentication fails.

**Describe alternatives you've considered**
The alternative is to save the job, then Build with Parameters, only to see a 4xx message or wrong data and keep fiddling back and forth.

**Additional context**
Refer to behavior of SCM Git client as an example.
Credential + no url == "Please  enter a REST endpoint"
Bad Credential + url == "Failed to connect to ... : <error msg>" 
Credential + url  => quiet success.

Press "Validate" button to get and display response. Not 100% how to present that, but a starting point would be SUCCESS / FAIL / No data

### PR DESCRIPTION
**Pull request by h1dden-da3m0n**
**Description**

This PR aims to improve the configuration validation of this plugin.
The original idea was provided by ianwilliams1 in #10.

**Tasks**

* [x] provide initial basic validation in the configuration screen (HTTP status codes)\
This now behaves like the default SVC validation, if authentication is required the validation will error.\
Once the correct credential gets provided update the REST endpoint field to trigger a re-validation.
* [x] provide a way to validate the whole config (validate button)
* [x] investigate why filter value is ignored in config validation (fix it)

**Tests**

* [x] Endpoint valid/not valid
* [x] Credentials Req'd / Not Req'd
* [x] Credentials Req'd but invalid supplied (Or Creds not req'd but supplied anyway)

**Changes**

* add basic HTTP validation logic to REST endpoint validation

**Issues**

* closes #10

### CODE REVIEW

**Comment by h1dden-da3m0n** [comment]
image
Note: The config here is valid, yet the Json-Path I use is on porous producing gibberish to showcase the debugging potential of this.

Okay, the "Test Configuration" button works as intended (so far, still needs a few test runs testing).

**Comment by ianwilliams1** [comment]
The payload validation presentation aspect looks good. Have the Credentials Required but not supplied or Bad Credentials supplied been tested and is the user presentation similar to SCM plugin? 
Have you tested the various scenarios ...
Endpoint valid/not valid,
Credentials Req'd / Not Req'd 
Credentials Req'd but invalid supplied (Or Creds not req'd but supplied anyway).
I don't see any additional tests to validate.

**Comment by h1dden-da3m0n** [comment]
Hey Ian, thank you for the test case descriptions ;-) 
Some of them I had already done/planed, regardless I really appreciate your input!

**Comment by h1dden-da3m0n** [comment]
And to answer your first question: Yes the validation for the Rest endpoint now works like the SCM validation.
image
image
image


Unfortunately, GitHub returns a 404 if you are not authorized to view a repository instead of a 403 but I currently have no endpoint that I could ping easily :frowning_face: 
(you have to take my word for it that if the API returns a 403 it gets displayed accordingly, as it is the same logic)

**Pull request merged**
