### PR TITLE
feat(select): add filter to select by using select2 library

### PR DESCRIPTION
**Pull request by h1dden-da3m0n**
### Description

This PR aims to improve the plugins UX with extra long drop-down lists by providing a filter for the available options.
It does so by using [Select2](https://github.com/select2/select2).
This PR also aims to make this plugin compatible with the switch from the ancient table layout that was recently replaced with divs+css in Jenkins core.
**WARNING**: with this the plugin will no longer support a Jenkins core version below this => This PR wont be merged b4 a LTS version including a Core version supporting this new layout gets released (i.e. 2.277.x)

### Changes

* Make Plugin tr > div compatible (drops backward compatibility though :confused:)
* Add Select2 to be bundled
* Add Select2-Bootstrap4-Theme to be bundled
* replace plane select element with Select2
* add newly required jQuery3 Plugin dependency (Select2 needs it)

### Issues

* #22 

### Preview

*Disclaimer*: this plugin does not provide any Jenkins theming, it just is capable of reacting to it

<details><summary>Light Theme</summary>
<p>

image
image

</p>
</details>

<details><summary>Dark Theme</summary>
<p>

image
image

</p>
</details>

### CODE REVIEW

**Comment by h1dden-da3m0n** [comment]
@ianwilliams1 well this took way WAY longer than I ever anticipated, sorry for that, however I have finally something I am satisfied with after a couple local test :smile:

**Comment by ianwilliams1** [comment]
> @ianwilliams1 well this took way WAY longer than I ever anticipated, sorry for that, however I have finally something I am satisfied with after a couple local test 😄
> 
> Note: this is a draft since I am waiting for the new Core LTS to launch

No chance it's 2.263.4 compatible ?

**Comment by h1dden-da3m0n** [comment]
> > @ianwilliams1 well this took way WAY longer than I ever anticipated, sorry for that, however I have finally something I am satisfied with after a couple local test smile
> > Note: this is a draft since I am waiting for the new Core LTS to launch
> 
> No chance it's 2.263.4 compatible ?

If I rip out the tr > div part I *should* be able to make it 2.263.x compatible. (the only thing that I am not 100% sure about is the css vars)
Anyway, I'll try tomorrow (its 2am local :sweat_smile:) and quickfire you a release if it turns out to be working

**Comment by ianwilliams1** [comment]
Hi @h1dden-da3m0n , appreciate all your efforts. It was my recollection the tabs to [divs UI change was actually available since 2.264](https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/#configuration-ui-tables-to-divs), just not the default. I fully expect many users will be stuck on on 2.264.x if other plugins are not yet updated, so the flexibility/forard/backward compatibility is nice.  Do not go out of your way just to accommodate me - we have not yet implemented in our PR instance yet.

**Comment by h1dden-da3m0n** [comment]
> Hi @h1dden-da3m0n , appreciate all your efforts. It was my recollection the tabs to [divs UI change was actually available since 2.264](https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/#configuration-ui-tables-to-divs), just not the default. I fully expect many users will be stuck on on 2.264.x if other plugins are not yet updated, so the flexibility/forard/backward compatibility is nice. Do not go out of your way just to accommodate me - we have not yet implemented in our PR instance yet.

you are indeed right, so I reworked my approach a bit. It still includes a baseline bump from `2.235.x` to `2.263.x`, however it can now work with both layout methods :tada: 

### Screenshots

<details><summary>2.263.x</summary>
<p>

image
image
image

</p>
</details>

<details><summary>2.277.x preview</summary>
<p>

image
image
image

</p>
</details>

**Comment by h1dden-da3m0n** [comment]
> Hi @h1dden-da3m0n , appreciate all your efforts. It was my recollection the tabs to [divs UI change was actually available since 2.264](https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/#configuration-ui-tables-to-divs), just not the default. I fully expect many users will be stuck on on 2.264.x if other plugins are not yet updated, so the flexibility/forard/backward compatibility is nice. Do not go out of your way just to accommodate me - we have not yet implemented in our PR instance yet.

you are indeed right, so I reworked my approach a bit. It still includes a baseline bump from `2.235.x` to `2.263.x`, however it can now work with both layout methods :tada: 

### Screenshots

<details><summary>2.263.x</summary>
<p>

image
image
image

</p>
</details>

<details><summary>2.277.x preview</summary>
<p>

image
image
image

</p>
</details>

Note: sorry I prefer dark-mode so most screens will end up with that on (but I test against both)

**Review by k3rnelpan1c-dev — APPROVED** [review]

**Comment by h1dden-da3m0n** [comment]
Okay 1.3.x is out and now has this PR in it! :tada: 
I did not find anything wrong with it, however if there is anything I have missed report the issue and I shall fix it ASAP.

**Pull request merged**
